---
# Localhost 인벤토리 (Self-hosted runner용)
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: ki
      ansible_become_pass: ""
      # 배포 경로
      game_server_path: ~/backend/game-server
      batch_server_path: ~/backend/batch-server
